data_for_All_alphabet = [
    // data for A
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A History of Bangladesh",
        type: "Book",
        authors: "Schendel William Van",
        ISBN10: "",
        ISBN13: " 9780521121903",
        category: "",
        edition: 1,
        publicationYear: 2009,
        callNo: "954.92 SCH 2009",
        publisher: "Cambridge University ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A 6th Bowl of Chicken Soup for the soul",
        type: "Book",
        authors: "Canfirld jack",
        ISBN10: "8187671211",
        ISBN13: "",
        category: "Genaral",
        edition: 1,
        publicationYear: 1999,
        callNo: "808.83 CAN 1999",
        publisher: " Westley Book",
        page: "385",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 2,
        library: "Gulshan",
    },

    // 3
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A Book of English Essay",
        type: "Book",
        authors: "Williams W. E.",
        ISBN10: "",
        ISBN13: "",
        category: "English ",
        edition: 1,
        publicationYear: 1967,
        callNo: "820 WIB 1967",
        publisher: "Penguin",
        page: "377",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    // 4
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A Civil Republic: Beyond Capitalism and Nationalism",
        type: "Book",
        authors: "Bruyn, Severyn T.",
        ISBN10: "1565491998  ",
        ISBN13: "9781565491991  ",
        category: "Unknown",
        edition: "",
        publicationYear: 2005,
        callNo: "300 BRC 2005 ",
        publisher: " Kumarian Press, Bangladesh",
        page: " 320 ",
        tags: "Social Sciences, Nationalism, Political Science",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    // 5
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A Communicative Grammar of English",
        type: "Book",
        authors: "Leech Geoffrey",
        ISBN10: "",
        ISBN13: "",
        category: "English ",
        edition: "",
        publicationYear: 1985,
        callNo: "300 BRC 2005 ",
        publisher: "Longman",
        page: "",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    // 6
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A Communicative Grammar of English",
        type: "Book",
        authors: "Leech Geoffrey",
        ISBN10: "0582552389 ",
        ISBN13: "",
        category: "English ",
        edition: "",
        publicationYear: 1975,
        callNo: "517edd22605c9 ",
        publisher: "Longman",
        page: "",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    // 7
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A Content-Based Grammar",
        type: "Book",
        authors: "Werner Patricia K,Nelson John P",
        ISBN10: "0070695814",
        ISBN13: "9780071149211",
        category: "English ",
        edition: "",
        publicationYear: 1996,
        callNo: "517edd22605c9 ",
        publisher: "McGraw-Hill ",
        page: "461",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    // 8
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A Content-Based Writing book : mosaic one ",
        type: "Book",
        authors: "Blass Laurie,Pike-baley M",
        ISBN10: "007112960X ",
        ISBN13: "9780071145244 ",
        category: "English ",
        edition: "",
        publicationYear: 1996,
        callNo: "411 BLC 1996",
        publisher: "McGraw-Hill ",
        page: "",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    // 9
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A Content-Based writing book : mosaic two ",
        type: "Book",
        authors: "Blass Laurie,Pike-baley M",
        ISBN10: "0071149139  ",
        ISBN13: "9780071149136 ",
        category: "English ",
        edition: "",
        publicationYear: 1996,
        callNo: "411 BLC 1996",
        publisher: "McGraw-Hill ",
        page: "",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    // 10
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A Course in Language Teaching Trainee Book Trainee's Book (Cambridge Teacher Training and Development) ",
        type: "Book",
        authors: "Ur, Penny",
        ISBN10: "0521656249   ",
        ISBN13: "9780521656245  ",
        category: "Unknown ",
        edition: "",
        publicationYear: 1999,
        callNo: "418.00721 URC 1999",
        publisher: "Cambridge University Press",
        page: "156",
        tags: "Instruction, Linguistics, English as a Second Language, Instruction Methods, Education, Foreign Languages ",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    // 11
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A Dictionary of American Proverbs",
        type: "Book",
        authors: "Mieder Wolfgang",
        ISBN10: "0195053990",
        ISBN13: "9780195053999   ",
        category: "Dictionary   ",
        edition: "",
        publicationYear: 1992,
        callNo: "R 398.921 DIC ",
        publisher: "Oxford",
        page: "710",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    // 12
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A Dictionary of Literary Terms and Literary Theory (Dictionary, Penguin)",
        type: "Book",
        authors: "Cuddon, J. A,Wolfgang",
        ISBN10: "0140512276",
        ISBN13: "9780140512274",
        category: "Unknown",
        edition: "",
        publicationYear: 1992,
        callNo: "R 398.921 DIC ",
        publisher: "Penguin Books",
        page: "1072",
        tags: "Literary, Reference, Philosophy, Literature ",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 2,
        library: "Gulshan",
    },
    // 13
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A Dictionary of Sociolinguistics",
        type: "Book",
        authors: "Swann, Joan Deumert, Ana  Mesthrie, Rajend Lillis, Theresa",
        ISBN10: "0817350977 ",
        ISBN13: "9780817350970",
        category: "Unknown",
        edition: "",
        publicationYear: 2004,
        callNo: "306.4403 SWD 2004",
        publisher: "University Alabama Press",
        page: "384",
        tags: "Linguistics ",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 2,
        library: "Gulshan",
    },
    // 14
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A First Course in Statistics",
        type: "Book",
        authors: "S Greer A",
        ISBN10: "0859500438  ",
        ISBN13: "",
        category: "Statistics  ",
        edition: "",
        publicationYear: 1988,
        callNo: "519 GRF 1988 	",
        publisher: " Stanity ",
        page: "384",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    // 15
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "A Glossary of Contemporary Literary Theory (Essential Glossary Series, 1)",
        type: "Book",
        authors: "Hawthorn, Jeremy",
        ISBN10: "0340761954   ",
        ISBN13: "9780340761953 ",
        category: "Unknown  ",
        edition: "",
        publicationYear: 2000,
        callNo: "809.91 HAG 2000",
        publisher: " Bloomsbury Academic",
        page: "416",
        tags: "Criticism & Theory, Reference ",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    /* A ENDS HERE */




    /* 
   l data starts-------------------
    */

    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Laboratory work in Hydraulics",
        type: "Book",
        authors: "Lomax ( Lomax W.R. )",
        ISBN10: "0340761954   ",
        ISBN13: "9780340761953 ",
        category: "Engineering  ",
        edition: "",
        publicationYear: 2000,
        callNo: "523.002 LOL 1979 C-1",
        publisher: "",
        page: "",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Labour and Industrial Laws of Bangladesh",
        type: "Book",
        authors: "Nirmalendu Dhar",
        ISBN10: "9847080003",
        ISBN13: "",
        category: "Law",
        edition: "",
        publicationYear: 2000,
        callNo: "344.5492 NIL 2000",
        publisher: "Khoshroz Kitab Mahal, United States ",
        page: " 1432 ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Labour and Industrial Laws of Bangladesh",
        type: "Book",
        authors: "Rofiuddin Md.,Khan A A",
        ISBN10: "",
        ISBN13: "",
        category: "Law",
        edition: "",
        publicationYear: 2004,
        callNo: "344.5492 RAW 2004",
        publisher: " Khoshroz kitab mahal",
        page: " 1324  ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Ladies Coupe",
        type: "Book",
        authors: "Nair Anita",
        ISBN10: "0141005955",
        ISBN13: "9780141005959",
        category: "Genaral",
        edition: "",
        publicationYear: 2001,
        callNo: "823 NAL 2001",
        publisher: "Penguin ",
        page: " 276   ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Lajja: Shame",
        type: "Book",
        authors: "Taslima Nasrin",
        ISBN10: "0140240519 ",
        ISBN13: "9780140240511",
        category: "Unknown  ",
        edition: "",
        publicationYear: 1994,
        callNo: "813.54 BRD 2003",
        publisher: " Penguin Books",
        page: " 215",
        tags: "Contemporary",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Language : introductory reading",
        type: "Book",
        authors: "Clark Rosa",
        ISBN10: "312467958  ",
        ISBN13: "",
        category: "English    ",
        edition: "",
        publicationYear: 1977,
        callNo: "401 CLL 1977",
        publisher: " ST.Martin ",
        page: " 528 ",
        tags: "Contemporary",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Language and Power in the Modern World",
        type: "Book",
        authors: "Talbot, Dr. Mary, Atkinson, Karen,Atkinson, David",
        ISBN10: "0817350691",
        ISBN13: "9780817350697",
        category: "Computer      ",
        edition: "",
        publicationYear: 2003,
        callNo: "",
        publisher: " University Alabama Press ",
        page: "  352  ",
        tags: " Linguistics, Study & Teaching",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Language Arts",
        type: "Book",
        authors: "McGraw-hill",
        ISBN10: "0022447105 ",
        ISBN13: "",
        category: "English",
        edition: "",
        publicationYear: 2001,
        callNo: "372.6 HAL 2001",
        publisher: " McGraw-Hill ",
        page: "  623   ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Language Arts",
        type: "Book",
        authors: "Hasbrouck Jan E.",
        ISBN10: "",
        ISBN13: "9780022449513 ",
        category: "English",
        edition: "",
        publicationYear: 2001,
        callNo: "372.6155 HAL 2001",
        publisher: " McGraw Hill, United States ",
        page: "  623   ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Language Arts",
        type: "Book",
        authors: "Hasbrouck Jan E.",
        ISBN10: "0022449493 ",
        ISBN13: "9780022449490",
        category: "English",
        edition: "",
        publicationYear: 2001,
        callNo: "372.6155 HAL 2001",
        publisher: " McGraw Hill, United States ",
        page: "  576   ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 2,
        library: "Gulshan",
    },

    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Language Customs and Protocol",
        type: "Book",
        authors: "Moore,Oliver,Vcady",
        ISBN10: "1560520973  ",
        ISBN13: "9781560520979 ",
        category: "English",
        edition: "",
        publicationYear: 1992,
        callNo: "400 MOL 1992",
        publisher: " Crisp ",
        page: "  124   ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Language in Use: Intermediate:Self study Workbook",
        type: "Book",
        authors: "Doff Adrian,Jones Christopher",
        ISBN10: " 0521435544",
        ISBN13: "9780521435543",
        category: "English",
        edition: "",
        publicationYear: 1994,
        callNo: "420 DO2 1994",
        publisher: " Cambridge  ",
        page: "   136    ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Language in Use: Pre-Intermediate:Self study Workbook",
        type: "Book",
        authors: "Doff Adrian,Jones Christopher",
        ISBN10: "",
        ISBN13: "9780521774055 ",
        category: "English",
        edition: "",
        publicationYear: 2000,
        callNo: "420 DO2 2000",
        publisher: " Cambridge  ",
        page: " 95",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },



    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Language in Use: Upper-intermediate",
        type: "Book",
        authors: "Doff Adrian,Jones Christopher",
        ISBN10: " 0521555493 ",
        ISBN13: "9780521555494  ",
        category: "English",
        edition: "",
        publicationYear: 1997,
        callNo: "420 DOL 1997",
        publisher: " Cambridge  ",
        page: " 95",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Language Policy",
        type: "Book",
        authors: "Spolsky Bernard",
        ISBN10: " 0521011752  ",
        ISBN13: "9780521011754   ",
        category: "English",
        edition: "",
        publicationYear: 2004,
        callNo: "306.449 SPL 2004",
        publisher: " Cambridge  ",
        page: " 95",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    /* 
    l data ends-------------------
    */


    /* 
    M data starts-------------------
    */











    /* 
    M data ends-------------------
    */
    /* 
    n data starts-------------------
    */












    /* 
    M data ends-------------------
    */







    /* 
       m,n,O,P JUNAEAD
    */

    /* 
    Q,R HASIBUL
    */

    /* 
    S,T NIPA 
    */


    /* data for u starts*/
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Ultimate Visual Dictionary ",
        type: "Book",
        authors: "Dorlink Kindersley",
        ISBN10: 143030124,
        ISBN13: 9780143030126,
        category: "Dictionary  [ Browse Items ]",
        edition: "",
        publicationYear: 1999,
        callNo: "403 DOR 1999",
        publisher: "Dorlink",
        page: "640",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Uncovering Grammar ",
        type: "Book",
        authors: "Thornbury Scott",
        ISBN10: 333952820,
        ISBN13: 9780333952825,
        category: "English  [ Browse Items ]",
        edition: "",
        publicationYear: 2001,
        callNo: "425 THU 2001",
        publisher: "MacMillan",
        page: 122,
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 2,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Under the Banyan Tree and 2 other stories",
        type: "Book",
        authors: "Narayan R.K.",
        ISBN10: 8185986142,
        ISBN13: 9780333952825,
        category: "English  [ Browse Items ]",
        edition: 2,
        publicationYear: 1985,
        callNo: "808.831 WAU 2001 ",
        publisher: "Indian Thought Publication, United States",
        page: 193,
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Understanding Business",
        type: "Book",
        authors: "Willam G Niekel Jaames M Mchugh and Susan M Mchugh",
        ISBN10: 72320540,
        ISBN13: 9780333952825,
        category: "",
        edition: "",
        publicationYear: 2005,
        callNo: "005.43 COL 1992 C-1",
        publisher: "McGraw Hill, United States",
        page: 710,
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 5,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Understanding Business",
        type: "Book",
        authors: 'Nickels William G."Mc Hugh James M. Mc Hugh Susan M."',
        ISBN10: "0072538767",
        ISBN13: 9780333952825,
        category: "Business  [ Browse Items ]",
        edition: "",
        publicationYear: 2005,
        callNo: "005.43 COL 1992 C-1",
        publisher: "McGraw Hill, United States",
        page: 707,
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 2,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Understanding Business",
        type: "Book",
        authors: 'Nickels William',
        ISBN10: "0072320540",
        ISBN13: 9780333952825,
        category: "Business  [ Browse Items ]",
        edition: 6,
        publicationYear: 2002,
        callNo: "650 NIU 2002 ",
        publisher: "McGraw Hill, United States",
        page: 707,
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Understanding Business",
        type: "Book",
        authors: 'Nickels William G,"James M Mc Hugh and Susan M.Mc Hugh"',
        ISBN10: "",
        ISBN13: 9780071101363,
        category: "Business  [ Browse Items ]",
        edition: 6,
        publicationYear: 2002,
        callNo: "650 NIO 2008",
        publisher: "McGraw Hill, United States",
        page: 707,
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Understanding Health Communication technologies ",
        type: "Book",
        authors: 'Whitten Pamela',
        ISBN10: "0787971057",
        ISBN13: 9780071101363,
        category: "",
        edition: 0,
        publicationYear: 2004,
        callNo: "610.28 WHU 2004",
        publisher: "Jossey-Bass",
        page: 364,
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Understanding Learning Disabilities",
        type: "Book",
        authors: 'Bryan Tanis',
        ISBN10: "874846080",
        ISBN13: 9780071101363,
        category: "English  [ Browse Items ] ",
        edition: 0,
        publicationYear: 1982,
        callNo: "",
        publisher: "",
        page: 382,
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Understanding Poetry : An Anthology For College",
        type: "Book",
        authors: 'Brooks , Cleanth Robbrt Penn Warren',
        ISBN10: "",
        ISBN13: "",
        category: "",
        edition: 0,
        publicationYear: 1938,
        callNo: "821.08 BRU 1938",
        publisher: "",
        page: 382,
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 2,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Understanding Psychology",
        type: "Book",
        authors: 'Feldman, Robert S',
        ISBN10: "0077280598  ",
        ISBN13: "9780071266499",
        category: "Philosophy and psychology  [ Browse Items ]",
        edition: 0,
        publicationYear: 2022,
        callNo: "",
        publisher: "",
        page: 382,
        tags: "Education & Training, General",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Understanding Psychology",
        type: "Book",
        authors: 'Feldman, Robert S',
        ISBN10: "007288665X",
        ISBN13: "9780071266499",
        category: "Psycology  [ Browse Items ]",
        edition: 0,
        publicationYear: 2005,
        callNo: "150 FEU 2005",
        publisher: "McGraw Hill, United States  ",
        page: 639,
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 5,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Understanding Second Language Acquisition ",
        type: "Book",
        authors: 'Ortega Lourdes',
        ISBN10: "007288665X",
        ISBN13: "9780071266499",
        category: "",
        edition: 0,
        publicationYear: "",
        callNo: "418.007 ORU 2011",
        publisher: 1985,
        page: "",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: " Understanding Second Language Acquisition ",
        type: "Book",
        authors: 'Ellis Rod',
        ISBN10: "",
        ISBN13: "",
        category: "",
        edition: 0,
        publicationYear: "Oxford University Press, United Kingdom",
        callNo: "418.007 ELU 1985",
        publisher: "Hodder Education, United States",
        page: "",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 2,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: " Understanding Second Language Acquisition (Oxford Applied Linguistics) ",
        type: "Book",
        authors: 'Ellis, Rod',
        ISBN10: "019437081X",
        ISBN13: "9780194370813",
        category: " Unknown  [ Browse Items ] ",
        edition: 0,
        publicationYear: 1989,
        callNo: "418.007 ELU 1985",
        publisher: "Hodder Education, United States",
        page: "",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 2,
        library: "Gulshan",
    },
    /* data for u ends*/

    // data for w starts
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Wake Me Up When the Data Is Over: How Organizations Use Stories to Drive Results   ",
        type: "Book",
        authors: "Silverman, Lori L.",
        ISBN10: "0787982709  ",
        ISBN13: "9780787982706  ",
        category: "Unknown  ",
        edition: "",
        publicationYear: 2006,
        callNo: "658.45 SIW 2006",
        publisher: " Jossey-Bass ",
        page: " 320 ",
        tags: "Motivation & Self-Improvement, Economics, Motivational, Processes & Infrastructure ",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 2,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Walk like a Giant Sell like a Madman: Americas# 1 Salesman ShowsYou how to Sell Anything",
        type: "Book",
        authors: "Roberts Ralph R ( Ralph R Roberts & Joe Kraynak ).",
        ISBN10: " 0-470-37281-4   ",
        ISBN13: "",
        category: "Genaral",
        edition: "",
        publicationYear: 2008,
        callNo: "333.330688 RoW 2008",
        publisher: " Wiley, United States ",
        page: "  249  ",
        tags: "General book",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 2,
        library: "Gulshan",
    },

    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Wall Street People: True Stories of Today's Masters and Moguls ",
        type: "Book",
        authors: "Ellis, Charles D.",
        ISBN10: " 0471238090 ",
        ISBN13: "9780471238096 ",
        category: "Unknown  ",
        edition: "",
        publicationYear: 2001,
        callNo: "332.60973 ELW 2001 ",
        publisher: "Wiley, United States ",
        page: "  342   ",
        tags: "Business, Finance, Investing, Management, Accounting, Economics, Investments & Securities ",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Washington Square",
        type: "Book",
        authors: "James Henry",
        ISBN10: " 0194228274  ",
        ISBN13: "9780194228275  ",
        category: "Genaral    ",
        edition: "",
        publicationYear: 1997,
        callNo: "332.60973 ELW 2001 ",
        publisher: "Oxford ",
        page: "   76    ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Wastewater Engineering",
        type: "Book",
        authors: "Metcalf Eddy",
        ISBN10: "0070495394",
        ISBN13: "",
        category: "Civil",
        edition: "",
        publicationYear: 2003,
        callNo: "628.3 MEW 2002 ",
        publisher: "Tata mcGraw-hill  ",
        page: "    1819     ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Watcom C : Graphics Library",
        type: "Book",
        authors: "Watcom Intl. Cop.",
        ISBN10: "",
        ISBN13: "",
        category: "Computers  ",
        edition: "",
        publicationYear: 2003,
        callNo: "	005.133 HIG 1992 ",
        publisher: "",
        page: " 1992 ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Watcom C : Language Reference",
        type: "Book",
        authors: "Watcom Intl. Cop.",
        ISBN10: "1550940333 ",
        ISBN13: "",
        category: "Computers  ",
        edition: "",
        publicationYear: 1991,
        callNo: "005.133 MCL 1991",
        publisher: "",
        page: " 276 ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Watcom C : Library",
        type: "Book",
        authors: "Watcom Intl. Cop.",
        ISBN10: " 1550940368  ",
        ISBN13: "",
        category: "General  ",
        edition: "",
        publicationYear: 1992,
        callNo: "005.133 CRW 1992 ",
        publisher: "",
        page: "520",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Watcom C : Linker",
        type: "Book",
        authors: "Watcom Intl. Cop.",
        ISBN10: " 155940384   ",
        ISBN13: "",
        category: "Computers",
        edition: "",
        publicationYear: 1992,
        callNo: "005.43 COL 1992 C-1",
        publisher: "",
        page: "344",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Watcom C/C++ : User Guide ",
        type: "Book",
        authors: "Watcom Intl. Cop.",
        ISBN10: " 1550940597    ",
        ISBN13: "",
        category: "Computers",
        edition: "",
        publicationYear: 1993,
        callNo: "005.133 WAW 1993",
        publisher: "",
        page: "576",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Baridhara",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Watcom Video user's guide",
        type: "Book",
        authors: "Watcom Intl. Cop.",
        ISBN10: "155094066X",
        ISBN13: "",
        category: "General",
        edition: "",
        publicationYear: 1993,
        callNo: "005.133 WAT 1993",
        publisher: "",
        page: "1993",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Water Resources Management and the Environment",
        type: "Book",
        authors: " Aswathanarayana U.",
        ISBN10: "90582451930",
        ISBN13: "",
        category: "Civil",
        edition: "",
        publicationYear: 2001,
        callNo: "005.133 WAT 1993",
        publisher: "Balkema ",
        page: "422 ",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Water Supply Engineering",
        type: "Book",
        authors: "grag ( Garg, S.K )",
        ISBN10: "8174091203 ",
        ISBN13: "",
        category: "Engineering",
        edition: "",
        publicationYear: "",
        callNo: "628.16 GAW 2004 C-2 	",
        publisher: " ",
        page: "",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Water supply & sanitation: Rural and low income urban communities        ",
        type: "Book",
        authors: "Ahmed, M. Feroze",
        ISBN10: "9843109368",
        ISBN13: "9789843109361",
        category: " Civil Engineering",
        edition: "",
        publicationYear: "2022",
        callNo: "628 ahw 2000 C-2 ",
        publisher: "  ITN-Bangladesh, Centre for Water Supply and Waste Management, BUET ",
        page: "444",
        tags: "Water Supply & Land Use",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 6,
        library: "Gulshan",
    },
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Water Supply and Sewerag",
        type: "Book",
        authors: "McGhee Terence",
        ISBN10: "0070609381",
        ISBN13: "",
        category: " Civil",
        edition: "",
        publicationYear: "1991",
        callNo: "628 MEW 1991",
        publisher: "McGraw-Hill",
        page: "606",
        tags: "Water Supply & Land Use",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 6,
        library: "Gulshan",
    },
    // data for w ends

    // data for y 16
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "You Can Hear Me Now",
        type: "Book",
        authors: "Sullivan Nicholas P. ( Nicholas P. Sullivan)",
        ISBN10: "0787986094",
        ISBN13: "",
        category: "",
        edition: "",
        publicationYear: 2007,
        callNo: "384.55091 NIY 2007",
        publisher: "Wiley, United States",
        page: "",
        tags: "General book",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },

    // data for z 16
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Zoom In! 1 Language Booster Workbook",
        type: "Book",
        authors: "Ingrid Freebairn",
        ISBN10: "0130939013   ",
        ISBN13: "9780130939012  ",
        category: "Unknown  ",
        edition: "",
        publicationYear: 2022,
        callNo: "769.5 ABP 2003 ",
        publisher: "Pearson English Language Teaching ",
        page: "",
        tags: "Schools & Teaching",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },


]



// 
/* 
const data = [
    {
        img: "https://i.ibb.co/mHmhd7j/empty-book-default-cover.png",
        title: "Ultimate Visual Dictionary ",
        type: "Book",
        authors: "Dorlink Kindersley",
        ISBN10: 143030124,
        ISBN13: 9780143030126,
        category: "Dictionary  [ Browse Items ]",
        edition: "",
        publicationYear: 1999,
        callNo: "403 DOR 1999",
        publisher: "Dorlink",
        page: "640",
        tags: "",
        abstract: "",
        description: "",
        biblioNotes: "",
        copies: 1,
        library: "Gulshan",
    },
 
]


*/